# Generated by Django 4.0 on 2022-03-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_thumbnail_alter_article_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='url',
            new_name='thumbnail_url',
        ),
    ]
